ItemTrig.gameEnums = {}

ItemTrig.gameEnums.alchemyEffectStrings = {
   [-1] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_BREACH),
   [-2] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_COWARDICE),
   [-3] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_DEFILE),
   [-4] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_DETECTION),
   [-5] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_ENERVATION),
   [-6] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_ENTRAPMENT),
   [-7] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_FRACTURE),
   [-8] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_GRADUALRAVAGEHEALTH),
   [-9] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_HINDRANCE),
   [-10] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_INCREASEARMOR),
   [-11] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_INCREASESPELLRESIST),
   [-12] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_INCREASEWEAPONPOWER),
   [-13] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_INVISIBLE),
   [-14] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_LINGERINGHEALTH),
   [-15] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_MAIM),
   [-16] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_PROTECTION),
   [-17] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_RAVAGEHEALTH),
   [-18] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_RAVAGEMAGICKA),
   [-19] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_RAVAGESTAMINA),
   [-20] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_RESTOREHEALTH),
   [-21] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_RESTOREMAGICKA),
   [-22] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_RESTORESTAMINA),
   [-23] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_SPEED),
   [-24] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_SPELLCRITICAL),
   [-25] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_UNCERTAINTY),
   [-26] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_UNSTOPPABLE),
   [-27] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_VITALITY),
   [-28] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_VULNERABILITY),
   [-29] = GetString(ITEMTRIG_STRING_ALCHEMYEFFECT_WEAPONCRITICAL),
}

do
   local styles = {}
   for i = 1, GetNumValidItemStyles() do
      local id   = GetValidItemStyleId(i)
      styles[id] = GetItemStyleName(id)
   end
   ItemTrig.gameEnums.styles = styles
end